import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/app/components/NavBar";
import { Antonio } from "next/font/google";

const antonio = Antonio({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${antonio.className} bg-neutral-darkBlue`}>
        <Navbar />

        <main className="">{children}</main>
      </body>
    </html>
  );
}
